USE [master]
GO
/****** Object:  Database [BugsClase03]    Script Date: 18/09/2018 03:05:00 p.m. ******/
CREATE DATABASE [BugsClase03]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BugsClase03', FILENAME = N'E:\Programas\SOLIDWORKS\MSSQL12.TEW_SQLEXPRESS\MSSQL\DATA\BugsClase03.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BugsClase03_log', FILENAME = N'E:\Programas\SOLIDWORKS\MSSQL12.TEW_SQLEXPRESS\MSSQL\DATA\BugsClase03_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [BugsClase03] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BugsClase03].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BugsClase03] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BugsClase03] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BugsClase03] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BugsClase03] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BugsClase03] SET ARITHABORT OFF 
GO
ALTER DATABASE [BugsClase03] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [BugsClase03] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BugsClase03] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BugsClase03] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BugsClase03] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BugsClase03] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BugsClase03] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BugsClase03] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BugsClase03] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BugsClase03] SET  ENABLE_BROKER 
GO
ALTER DATABASE [BugsClase03] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BugsClase03] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BugsClase03] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BugsClase03] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BugsClase03] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BugsClase03] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BugsClase03] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BugsClase03] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BugsClase03] SET  MULTI_USER 
GO
ALTER DATABASE [BugsClase03] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BugsClase03] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BugsClase03] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BugsClase03] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [BugsClase03] SET DELAYED_DURABILITY = DISABLED 
GO
USE [BugsClase03]
GO
/****** Object:  Table [dbo].[CLASIFICACION]    Script Date: 18/09/2018 03:05:00 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLASIFICACION](
	[codigoClasificacion] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](30) NOT NULL,
	[descripcion] [varchar](200) NOT NULL,
 CONSTRAINT [PK_CLASIFICACION] PRIMARY KEY CLUSTERED 
(
	[codigoClasificacion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CLIENTES]    Script Date: 18/09/2018 03:05:00 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLIENTES](
	[codigoCliente] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](30) NOT NULL,
	[apellido] [varchar](30) NOT NULL,
	[telefono] [varchar](50) NOT NULL,
	[cuit] [int] NOT NULL,
 CONSTRAINT [PK_CLIENTES] PRIMARY KEY CLUSTERED 
(
	[codigoCliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DETALLE_VENTA]    Script Date: 18/09/2018 03:05:00 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DETALLE_VENTA](
	[numeroLote] [int] NOT NULL,
	[codigoProducto] [int] NOT NULL,
	[numeroVenta] [int] NOT NULL,
	[cantidad] [int] NOT NULL,
	[precioVenta] [money] NOT NULL,
 CONSTRAINT [PK_DETALLE_VENTA] PRIMARY KEY CLUSTERED 
(
	[numeroLote] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOTES]    Script Date: 18/09/2018 03:05:00 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOTES](
	[numeroLote] [int] NOT NULL,
	[codigoProveedor] [int] NOT NULL,
	[codigoProducto] [int] NOT NULL,
	[stockInicial] [int] NOT NULL,
	[stockActual] [int] NOT NULL,
	[fechaIngreso] [date] NOT NULL,
 CONSTRAINT [PK_LOTES] PRIMARY KEY CLUSTERED 
(
	[numeroLote] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUCTOS]    Script Date: 18/09/2018 03:05:00 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCTOS](
	[codigoProducto] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](50) NOT NULL,
	[descripcion] [varchar](200) NOT NULL,
	[precio] [money] NOT NULL,
	[clasificacion] [int] NOT NULL,
 CONSTRAINT [PK_PRODUCTOS] PRIMARY KEY CLUSTERED 
(
	[codigoProducto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PROVEEDOR]    Script Date: 18/09/2018 03:05:00 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROVEEDOR](
	[codigoProveedor] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](30) NOT NULL,
	[apellido] [varchar](30) NOT NULL,
	[direccion] [varchar](50) NOT NULL,
	[telefono] [varchar](50) NOT NULL,
 CONSTRAINT [PK_PROVEEDOR] PRIMARY KEY CLUSTERED 
(
	[codigoProveedor] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PROVxPROD]    Script Date: 18/09/2018 03:05:00 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROVxPROD](
	[codigoProveedor] [int] NOT NULL,
	[codigoProducto] [int] NOT NULL,
	[tiempoEntrega] [int] NOT NULL,
	[precio] [money] NOT NULL,
 CONSTRAINT [PK_PROVXPROD] PRIMARY KEY CLUSTERED 
(
	[codigoProveedor] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPO_FACTURA]    Script Date: 18/09/2018 03:05:00 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPO_FACTURA](
	[codigoTipo] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](10) NOT NULL,
 CONSTRAINT [PK_TIPO_FACTURA] PRIMARY KEY CLUSTERED 
(
	[codigoTipo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPO_USUARIO]    Script Date: 18/09/2018 03:05:00 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPO_USUARIO](
	[codigoTipo] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](10) NOT NULL,
	[activo] [bit] NOT NULL,
 CONSTRAINT [PK_TIPO_USUARIO] PRIMARY KEY CLUSTERED 
(
	[codigoTipo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USUARIO]    Script Date: 18/09/2018 03:05:00 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIO](
	[legajo] [int] IDENTITY(1,1) NOT NULL,
	[fechaIngreso] [date] NOT NULL,
	[telefono] [varchar](50) NOT NULL,
	[fechaNacimiento] [date] NOT NULL,
	[nombre] [varchar](30) NOT NULL,
	[apellido] [varchar](30) NOT NULL,
	[password] [varchar](250) NOT NULL,
	[tipo] [int] NOT NULL,
	[ultimoLogin] [datetime] NOT NULL,
	[activo] [bit] NOT NULL,
 CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED 
(
	[legajo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VENTAS]    Script Date: 18/09/2018 03:05:00 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VENTAS](
	[numeroVenta] [int] IDENTITY(1,1) NOT NULL,
	[tipoFactura] [int] NOT NULL,
	[vendedor] [int] NOT NULL,
	[cliente] [int] NOT NULL,
	[fecha] [date] NOT NULL,
 CONSTRAINT [PK_VENTAS] PRIMARY KEY CLUSTERED 
(
	[numeroVenta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TIPO_USUARIO] ADD  CONSTRAINT [DF_TIPO_USUARIO_activo]  DEFAULT ((1)) FOR [activo]
GO
ALTER TABLE [dbo].[DETALLE_VENTA]  WITH CHECK ADD  CONSTRAINT [DETALLE_VENTA_fk0] FOREIGN KEY([numeroLote])
REFERENCES [dbo].[LOTES] ([numeroLote])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[DETALLE_VENTA] CHECK CONSTRAINT [DETALLE_VENTA_fk0]
GO
ALTER TABLE [dbo].[DETALLE_VENTA]  WITH CHECK ADD  CONSTRAINT [DETALLE_VENTA_fk1] FOREIGN KEY([codigoProducto])
REFERENCES [dbo].[PRODUCTOS] ([codigoProducto])
GO
ALTER TABLE [dbo].[DETALLE_VENTA] CHECK CONSTRAINT [DETALLE_VENTA_fk1]
GO
ALTER TABLE [dbo].[DETALLE_VENTA]  WITH CHECK ADD  CONSTRAINT [DETALLE_VENTA_fk2] FOREIGN KEY([numeroVenta])
REFERENCES [dbo].[VENTAS] ([numeroVenta])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[DETALLE_VENTA] CHECK CONSTRAINT [DETALLE_VENTA_fk2]
GO
ALTER TABLE [dbo].[LOTES]  WITH CHECK ADD  CONSTRAINT [LOTES_fk0] FOREIGN KEY([codigoProveedor])
REFERENCES [dbo].[PROVEEDOR] ([codigoProveedor])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[LOTES] CHECK CONSTRAINT [LOTES_fk0]
GO
ALTER TABLE [dbo].[LOTES]  WITH CHECK ADD  CONSTRAINT [LOTES_fk1] FOREIGN KEY([codigoProducto])
REFERENCES [dbo].[PRODUCTOS] ([codigoProducto])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[LOTES] CHECK CONSTRAINT [LOTES_fk1]
GO
ALTER TABLE [dbo].[PRODUCTOS]  WITH CHECK ADD  CONSTRAINT [PRODUCTOS_fk0] FOREIGN KEY([clasificacion])
REFERENCES [dbo].[CLASIFICACION] ([codigoClasificacion])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[PRODUCTOS] CHECK CONSTRAINT [PRODUCTOS_fk0]
GO
ALTER TABLE [dbo].[PROVxPROD]  WITH CHECK ADD  CONSTRAINT [PROVxPROD_fk0] FOREIGN KEY([codigoProveedor])
REFERENCES [dbo].[PROVEEDOR] ([codigoProveedor])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[PROVxPROD] CHECK CONSTRAINT [PROVxPROD_fk0]
GO
ALTER TABLE [dbo].[PROVxPROD]  WITH CHECK ADD  CONSTRAINT [PROVxPROD_fk1] FOREIGN KEY([codigoProducto])
REFERENCES [dbo].[PRODUCTOS] ([codigoProducto])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[PROVxPROD] CHECK CONSTRAINT [PROVxPROD_fk1]
GO
ALTER TABLE [dbo].[USUARIO]  WITH CHECK ADD  CONSTRAINT [USUARIO_fk0] FOREIGN KEY([tipo])
REFERENCES [dbo].[TIPO_USUARIO] ([codigoTipo])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[USUARIO] CHECK CONSTRAINT [USUARIO_fk0]
GO
ALTER TABLE [dbo].[VENTAS]  WITH CHECK ADD  CONSTRAINT [VENTAS_fk0] FOREIGN KEY([tipoFactura])
REFERENCES [dbo].[TIPO_FACTURA] ([codigoTipo])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[VENTAS] CHECK CONSTRAINT [VENTAS_fk0]
GO
ALTER TABLE [dbo].[VENTAS]  WITH CHECK ADD  CONSTRAINT [VENTAS_fk1] FOREIGN KEY([vendedor])
REFERENCES [dbo].[USUARIO] ([legajo])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[VENTAS] CHECK CONSTRAINT [VENTAS_fk1]
GO
ALTER TABLE [dbo].[VENTAS]  WITH CHECK ADD  CONSTRAINT [VENTAS_fk2] FOREIGN KEY([cliente])
REFERENCES [dbo].[CLIENTES] ([codigoCliente])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[VENTAS] CHECK CONSTRAINT [VENTAS_fk2]
GO
USE [master]
GO
ALTER DATABASE [BugsClase03] SET  READ_WRITE 
GO
